kind: StatefulSet
apiVersion: "apps/v1beta1"
metadata:
  name: orientdbservice
spec:
  serviceName: orientdbservice
  replicas: 2
  template:
    metadata:
      labels:
        service: orientdb
        type: container-deployment
    spec:
      containers:
      - name: orientdbservice
        image: orientdb-dist
        imagePullPolicy: Never
        env:
        - name: ORIENTDB_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 2424
          name: port-binary
        - containerPort: 2480
          name: port-http
        volumeMounts:
        - mountPath: /orientdb/databases
          name: orientdb-data
          subPath: databases
  volumeClaimTemplates:
  - metadata:
      name: orientdb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi